### ISSUE TITLE
Create a setup guide for first time users

### ISSUE THREAD

**Issue by SpookyTabz** [giawa/GiawaOS#1] opened 2021-12-21 23:27 UTC
make a setup guide that will say what u need to have installed, so people dont need try out multiple extensions

**Comment by giawa** [comment] 2021-12-22 17:56
Hi there, thanks for the comment!  I've extended the README to include a `Getting Started` section.  Does that help clear things up?

**Comment by giawa** [comment] 2021-12-26 20:57
Closing this for now as I am hopeful the issue is resolve.  Feel free to open it again if you have any questions.  Thanks!

**Closed as completed by giawa** 2021-12-26 20:57 UTC
